owi-arduino: src/SerialHelper.cpp File Reference
SerialHelper.cpp File Reference
#include <Arduino.h>
#include "SerialHelper.hh"
#include <Arduino_FreeRTOS.h>
Functions
oLoopCtrl getCtrInput ()
int getInt ()
int displayMenu (const char *menu, int numOfChoices)
Function Documentation
displayMenu()
int displayMenu (const char * menu, int numOfChoice)
display a menu passed in as String, and get user's choice index start at 0 to number of choice - 1
Parameters
menu string
numOfChoice number of choices
Returns
user's input
Definition at line 90 of file SerialHelper.cpp.
References getInt().
Referenced by task_Serial().
{
     Serial.print(menu);
     int choice = -1;
     do {
         choice = getInt();
     } while (choice < 0 || choice > numOfChoices - 1);
     return choice;
 }
getCtrInput()
oLoopCtrl getCtrInput ()
get the parametters for manual control of each joints
Definition at line 42 of file SerialHelper.cpp.
References oLoopCtrl::direction, oLoopCtrl::duration, getInt(), oLoopCtrl::i, MOTOR::NEG, MOTOR::POS, and oLoopCtrl::pwm.
{
     oLoopCtrl recv = {};
     int number = -1;
     while (number < 0 || number > 4) {
         Serial.print("\nEnter joint index\n");
         number = getInt();
     }
     recv.i = number;
     char dir = ' ';
     while (dir != 'r' && dir !='l') {
         Serial.print("\nEnter direction (l/r)\n");
         while(!Serial.available()) vTaskDelay(100/portTICK_PERIOD_MS);
         dir = Serial.read();
     }
     (dir == 'r') ? (recv.direction = MOTOR::DIR::POS) :
                    (recv.direction = MOTOR::DIR::NEG);
     number = -1;
     while (number < 0 || number > 255) {
         Serial.print("\nEnter power (0-255)\n");
         number = getInt();
     }
     recv.pwm = number;
     number = -1;
     while (number < 0) {
         Serial.print("\nEnter duration (ms)\n");
         number = getInt();
     }
     recv.duration = number;
     return recv;
 }
getInt()
int getInt ()
get an interger from Serial stream the method used is not safe, betting on correct data format only used temporarily
Definition at line 79 of file SerialHelper.cpp.
Referenced by displayMenu(), getCtrInput(), and JOINT::pid_test().
              {
     char buffer[10];
     while(!Serial.available()) vTaskDelay(100/portTICK_PERIOD_MS);
     int length = Serial.readBytesUntil('\n', buffer, 10);
     buffer[length] = '\0';      //terminate received string
     int number = atoi(buffer);
     Serial.println(number);
     return number;
 }