owi-arduino: L298N Class Reference
L298N Class Reference
#include <motor.hh>
Public Member Functions
L298N (uint8_t enPin, uint8_t in1Pin, uint8_t in2Pin)
void setDuration (long duration)
void output () override
void reverse ()
Public Member Functions inherited from MOTOR
MOTOR ()
void update (DIR direction, uint8_t power)
void setDirection (DIR direction)
void setPower (uint8_t power)
Additional Inherited Members
Public Types inherited from MOTOR
enum DIR { DIR::POS, DIR::NEG }
Protected Attributes inherited from MOTOR
DIR dir {DIR::POS}
uint8_t pwm {0}
float pos {0.0}
const float homePos {0.0}
float targetPos {0.0}
Detailed Description
L298N motor driver with arduino
Definition at line 64 of file motor.hh.
Constructor & Destructor Documentation
L298N()
L298N::L298N (uint8_t enPin, uint8_t in1Pin, uint8_t in2Pin)
Constructor
Definition at line 19 of file motor.cpp.
                                                           :
              enP(enPin), in1P(in1Pin), in2P(in2Pin), dur(0) {
     pinMode(enP, OUTPUT);
     pinMode(in1P, OUTPUT);
     pinMode(in2P, OUTPUT);
 }
Member Function Documentation
output()
void L298N::output () override virtual
perform the motion for set duration if dur == -1 drive in continous mode (WARNING: continous mode will output non stop, need to be called repeatedly to change speed/stop)
Implements MOTOR.
Definition at line 30 of file motor.cpp.
References MOTOR::dir, MOTOR::NEG, MOTOR::POS, and MOTOR::pwm.
Referenced by JOINT::actuate(), JOINT::halt(), reverse(), JOINT::test_step_neg(), and JOINT::test_step_pos().
                    {
     switch (dir) {
         case DIR::POS:
             digitalWrite(in1P, 0);
             digitalWrite(in2P, 1);
             break;
         case DIR::NEG:
             digitalWrite(in1P, 1);
             digitalWrite(in2P, 0);
             break;
         default:
             break;
     }
     analogWrite(enP, pwm);
     if (dur != -1) {
        delay(dur);
        analogWrite(enP, 0);
     }
 }
reverse()
void L298N::reverse ()
perform reverse of last motion
Definition at line 54 of file motor.cpp.
References MOTOR::dir, MOTOR::NEG, output(), and MOTOR::POS.
                     {
     if (dir == DIR::POS) {
         dir = DIR::NEG;
     } else {
         dir = DIR::POS;
     }
     output();
 }
setDuration()
void L298N::setDuration (long duration)
set duration of the motion
Parameters
duration time motor run in ms
Definition at line 26 of file motor.cpp.
Referenced by JOINT::actuate(), JOINT::halt(), JOINT::test_step_neg(), and JOINT::test_step_pos().
{
     dur = duration;
 }
The documentation for this class was generated from the following files:
include/motor.hh
src/motor.cpp