owi-arduino: POTENTIO Class Reference
POTENTIO Class Reference
#include <rotsensor.hh>
Public Member Functions
POTENTIO (uint8_t pin, unsigned bits, float range, float scale)
int getRawVal () override
float getVoltVal ()
float getDegreeVal () override
Additional Inherited Members
Protected Attributes inherited from ROTENCODER
int rawVal {0}
float degree {0.0}
Detailed Description
Class represent a rotational potentiometer
Definition at line 24 of file rotsensor.hh.
Constructor & Destructor Documentation
POTENTIO()
POTENTIO::POTENTIO (uint8_t pin, unsigned bits, float range, float scale)
constructor
Parameters
pin analog input pin
bits bits of resolution
range analog read voltage range
scale conversion factor voltage to degree
Definition at line 4 of file rotsensor.cpp.
                                                                         :
     pin(_pin), res(range/pow(2,bits)), scale(_scale) {}
Member Function Documentation
getDegreeVal()
float POTENTIO::getDegreeVal () override virtual
get the degree value
Returns
the degree value
Reimplemented from ROTENCODER.
Definition at line 24 of file rotsensor.cpp.
References ROTENCODER::degree, and getVoltVal().
Referenced by JOINT::getAngle(), JOINT::test_step_neg(), and JOINT::test_step_pos().
{
     getVoltVal();
     // low pass filter
     static bool firstpass = true;
     static const float coef = 0.5;
     if (firstpass) {
         degree = volt*scale;
         firstpass = false;
     } else {
         degree = coef*degree + (1.0 - coef)*(volt * scale);
     }
     return degree;
 }
getRawVal()
int POTENTIO::getRawVal () override virtual
get the raw value
Returns
the raw value
Implements ROTENCODER.
Definition at line 7 of file rotsensor.cpp.
References ROTENCODER::rawVal.
Referenced by getVoltVal().
{
     // //averaging filter
     // rawVal = 0;
     // for (int i = 0; i < 4; i++) {
     //     rawVal += analogRead(pin);
     // }
     // rawVal /= 4;
     rawVal = analogRead(pin);
     return rawVal;
 }
getVoltVal()
float POTENTIO::getVoltVal ()
get the voltage value
Returns
the voltage value
Definition at line 18 of file rotsensor.cpp.
References getRawVal(), and ROTENCODER::rawVal.
Referenced by getDegreeVal().
{
     getRawVal();
     volt = rawVal * res;
     return volt;
 }
The documentation for this class was generated from the following files:
include/rotsensor.hh
src/rotsensor.cpp