owi-arduino: MOTOR Class Reference
MOTOR Class Reference abstract
#include <motor.hh>
Public Types
enum DIR { DIR::POS, DIR::NEG }
Public Member Functions
MOTOR ()
void update (DIR direction, uint8_t power)
virtual void output ()=0
void setDirection (DIR direction)
void setPower (uint8_t power)
Protected Attributes
DIR dir {DIR::POS}
uint8_t pwm {0}
float pos {0.0}
const float homePos {0.0}
float targetPos {0.0}
Detailed Description
Abstract motor driver class
Definition at line 9 of file motor.hh.
Member Enumeration Documentation
DIR
enum MOTOR::DIR strong
direction of movement, implementation defined POS - positive direction NEG - negative direction
Enumerator
POS
NEG
Definition at line 17 of file motor.hh.
                    {
         POS,
         NEG
     };
Constructor & Destructor Documentation
MOTOR()
MOTOR::MOTOR ()
Constructor
Definition at line 4 of file motor.cpp.
 {}
Member Function Documentation
output()
virtual void MOTOR::output () pure virtual
perform the motion
Implemented in L298N.
setDirection()
void MOTOR::setDirection (DIR direction)
set rotational direction
Definition at line 11 of file motor.cpp.
References dir.
Referenced by JOINT::actuate(), JOINT::test_step_neg(), JOINT::test_step_pos(), and update().
{
     dir = direction;
 }
setPower()
void MOTOR::setPower (uint8_t power)
set duty cycle
Definition at line 15 of file motor.cpp.
References pwm.
Referenced by JOINT::actuate(), JOINT::halt(), JOINT::test_step_neg(), JOINT::test_step_pos(), and update().
{
     pwm = power;
 }
update()
void MOTOR::update (DIR direction, uint8_t power)
new control parametters
Definition at line 6 of file motor.cpp.
References setDirection(), and setPower().
{
     setDirection(direction);
     setPower(power);
 }
Member Data Documentation
dir
DIR MOTOR::dir {DIR::POS} protected
rotation direction
Definition at line 46 of file motor.hh.
Referenced by L298N::output(), L298N::reverse(), and setDirection().
homePos
const float MOTOR::homePos {0.0} protected
home position
Definition at line 55 of file motor.hh.
pos
float MOTOR::pos {0.0} protected
rotational position
Definition at line 52 of file motor.hh.
pwm
uint8_t MOTOR::pwm {0} protected
duty cycle (0-255)
Definition at line 49 of file motor.hh.
Referenced by L298N::output(), and setPower().
targetPos
float MOTOR::targetPos {0.0} protected
target position
Definition at line 58 of file motor.hh.
The documentation for this class was generated from the following files:
include/motor.hh
src/motor.cpp