owi-arduino: src/main.cpp File Reference
main.cpp File Reference
#include <Arduino.h>
#include <avr/sleep.h>
#include <Arduino_FreeRTOS.h>
#include <timers.h>
#include "ros.h"
#include "robotjoint.hh"
#include "jointconfig.hh"
#include "SerialHelper.hh"
Functions
void cmdCallback (const owi::position_cmd &cmd)
void task_ROS (void *pvParams)
void task_Serial (void *pvParams)
void task_actuate (void *pvParams)
void setup ()
void loop ()
Variables
ROSSERIAL rosserial & cmdCallback
volatile bool ROSctrl = false
JOINT joint [5]
Function Documentation
cmdCallback()
void cmdCallback (const owi::position_cmd & cmd)
Callback for ROS whenever a new command is received. Handle updating target angle
Definition at line 44 of file main.cpp.
References ROSctrl, and JOINT::setTarget().
{
     if (!ROSctrl) return;
     //Serial.println("Received a command");
     for (int i = 0; i < 5; i++) {
         //Serial.println(cmd.position[i]);
         joint[i].setTarget(cmd.position[i]);
     }
 }
loop()
void loop ()
Idle task
Definition at line 129 of file main.cpp.
             {
     sleep_cpu();
 }
setup()
void setup ()
Definition at line 32 of file main.cpp.
References task_actuate(), task_ROS(), and task_Serial().
              {
     set_sleep_mode(SLEEP_MODE_IDLE);
     sleep_enable();
     Serial.begin(9600);
     rosserial.init(115200);
     xTaskCreate(&task_ROS, "ROS", 512, NULL, 0, NULL);
     xTaskCreate(&task_Serial, "MENU", 512, NULL, 0, NULL);
     xTaskCreate(&task_actuate, "ACTUATE", 512, NULL, 1, NULL);
 }
task_actuate()
void task_actuate (void * pvParams)
Handle actuation of joints
Definition at line 114 of file main.cpp.
References JOINT::actuate(), and ROSctrl.
Referenced by setup().
{
     while(!ROSctrl) {
         vTaskDelay(100);
     }
     TickType_t xLastWakeTime = xTaskGetTickCount();
     while(true) {
         for (int i = 0; i < 5; i++) {
             joint[i].actuate();
         }
         vTaskDelayUntil(&xLastWakeTime, 5);
     }
 }
task_ROS()
void task_ROS (void * pvParams)
Handle ROS communication
Definition at line 54 of file main.cpp.
References JOINT::getAngle().
Referenced by setup().
{
     TickType_t xLastWakeTime = xTaskGetTickCount();
     while(true) {
         rosserial.putMsg("Hello");
         float angle[] = {joint[0].getAngle(),
                          joint[1].getAngle(),
                          joint[2].getAngle(),
                          joint[3].getAngle(),
                          joint[4].getAngle()};
         rosserial.putState(angle, 5);
         rosserial.update();
         vTaskDelayUntil(&xLastWakeTime, 10);
     }
 }
task_Serial()
void task_Serial (void * pvParams)
Handle serial communication
Definition at line 69 of file main.cpp.
References displayMenu(), JOINT::pid_test(), and ROSctrl.
Referenced by setup().
{
     static char menu[] = "\n=======================================\n"
                          "0 - Peform initial joint direction test\n"
                          "1 - Perform pid movement test\n"
                          "2 - Pass control to ROS\n";
     while(true) {
         int choice = displayMenu(menu, 3);
         switch (choice) {
         case 0: //initial step test
             {
             int i = displayMenu("\nEnter joint index\n",5);
             if (joint[i].test_step_pos()) {
                 Serial.println("Positive direction test PASSED");
             } else {
                 Serial.println("Positive direction test FAILED");
             }
             if (joint[i].test_step_neg()) {
                 Serial.println("Negative direction test PASSED");
             } else {
                 Serial.println("Negative direction test FAILED");
             }
             }
             break;
         case 1: //PID test
             {
             int i = displayMenu("\nEnter joint index\n", 5);
             joint[i].pid_test();
             }
             break;
         case 2: //start ros node mode
             ROSctrl = true;
             vTaskSuspend(NULL);
             break;
         default:
             break;
         }
     }
 }
Variable Documentation
cmdCallback
void cmdCallback
Definition at line 22 of file main.cpp.
joint
JOINT joint[5]
Initial value:
= {JOINT(joint0conf),
                  JOINT(joint1conf),
                  JOINT(joint2conf),
                  JOINT(joint3conf),
                  JOINT(joint4conf) }
Definition at line 25 of file main.cpp.
ROSctrl
volatile bool ROSctrl = false
Definition at line 23 of file main.cpp.
Referenced by cmdCallback(), task_actuate(), and task_Serial().